"""Agregar tabla logs_clima para registros de calidad del aire

Revision ID: 2f316ab84345
Revises: 
Create Date: 2025-12-17 18:54:58.933839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f316ab84345'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs_clima',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ciudad', sa.String(length=200), nullable=False),
    sa.Column('pais', sa.String(length=10), nullable=False),
    sa.Column('aqi', sa.Integer(), nullable=False),
    sa.Column('co', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('no2', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('o3', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('so2', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pm2_5', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('pm10', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('nh3', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('latitud', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('longitud', sa.DECIMAL(precision=10, scale=6), nullable=True),
    sa.Column('usuario_id', sa.String(length=50), nullable=True),
    sa.Column('proyecto_id', sa.String(length=50), nullable=True),
    sa.Column('fecha_consulta', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logs_clima')
    # ### end Alembic commands ###
